### PR TITLE
grab the url with query params to send to google instead of just the pat...

### PR DESCRIPTION
**Pull request by namkn**
grab the url with query params to send to google analytics instead of just the path

### CODE REVIEW

**Comment by justinsa** [comment]
Better straightforward change here.

**Comment by justinsa** [comment]
Sorry, meant "pretty straightforward change here" not "better". Autocorrect fail.

**Comment by revolunet** [comment]
i'm not really awaye if this change can cause any issue in tracking... @deltaepsilon @adam187 @justinsa ?

**Comment by adam187** [comment]
@revolunet This example (https://developers.google.com/analytics/devguides/collection/analyticsjs/pages#overriding) shows that 
you can indeed pass query params in pageview, but i couldn't find any example for old version.  

I think it would be better to add this as option since some people may not want to include query params in their stats.

**Comment by deltaepsilon** [comment]
@revolunet @adam187 @namkn I agree. I do not personally want to track parameters in my applications. Can this pull request be modified to make it an option? There should also be a description of how to activate it in the README, and a test would be nice as well.

**Comment by adam187** [comment]
@revolunet @namkn Now it looks good :)

**Comment by revolunet** [comment]
great, thanks everyone for the quick feedback ! opensource FTW !

**Pull request merged**
