### PR TITLE
Update angular-google-analytics.js

### PR DESCRIPTION
**Pull request by IdoHakimi**
Fixed _send by sending the object as many parameters as needed.
Fixed _trackCart changed 'to cart' to ' to cart', it missed a space.

### CODE REVIEW

**Comment by revolunet** [comment]
ok for everyone ? @deltaepsilon @justinsa @adam187

**Comment by adam187** [comment]
:thumbsup:

**Comment by justinsa** [comment]
:+1

**Comment by justinsa** [comment]
Bah! Stupid phones. This is a good change.

**Comment by revolunet** [comment]
thanks guys and @IdoHakimi for the change

**Pull request merged**
