### PR TITLE
auto page tracking fix

### PR DESCRIPTION
**Pull request by theromis**

### CODE REVIEW

**Comment by Toxantron** [comment]
Correct me if I am wrong, but this is not a fix. It simply alters the module to use `ui-router` events. If you use that module please just configure `Analytics` to use the event you want as described in the documentation. But this PR is not a fix but alters the default behaviour of the library.

**Comment by Toxantron** [comment]
Sample code from documentation:

    AnalyticsProvider.setEvent('$stateChangeSuccess')

**Comment by justinsa** [comment]
As @Toxantron points out, this isn't a fix, but a configuration option that is described in the readme.

**Comment by theromis** [comment]
it was strange for me that code doesn't work by default and requires "tuning" before is starts reporting

**Comment by justinsa** [comment]
That is because you are using ui-router instead of ng-route. ui-router is not the default implementation of routing in Angular.
On May 9, 2016 10:46 AM, Roman Vasilyev <notifications@github.com> wrote:it was strange for me that code doesn't work by default and requires "tuning" before is starts reporting

**Pull request closed without merging**
