### PR TITLE
Added gaTrackEvent directive

### PR DESCRIPTION
**Pull request by tsov**
https://github.com/revolunet/angular-google-analytics/issues/58

This is just a proposal to add some helper directives to minimise code on controllers. So you can declaratively define events inside HTML markup.

Example:

```HTML
<div ga-track-event="['button', 'click', 'Some Button']">test</div>
```

### CODE REVIEW

**Comment by deltaepsilon** [comment]
We should be careful about how much functionality we add to this library. We could include plenty of useful directives, but we might lose focus on the one thing that this lib does best; it provides an Angular service for interacting with Google Analytics.

That being said, if we're going to include any directives at all, this is the one to include. And thank you @tsov for writing a test to go along with it! We could probably use a new line in the README as well... but that ***is*** getting a little greedy.

@revolunet What are your thoughts?

**Comment by tsov** [comment]
In case you wonder, I changed the directive a little to not create an isolated scope, so it won't conflict with other directives.

@deltaepsilon Thanks! Want me to provide a line or two on directive usage in the description?

**Comment by deltaepsilon** [comment]
@tsov Any addition to the README is welcome! And removing isolate scope is always nice. I have a love/hate relationship with Angular's directives... and removing isolate scope where possible is a great idea.

**Comment by simonwalsh** [comment]
+1 for this directive, @tsov! I was gonna make one PR for this as well. This is likely to be used in all the projects I'm working on!

**Comment by simonwalsh** [comment]
Any idea when this will be merged @deltaepsilon ?

**Comment by deltaepsilon** [comment]
@tsov @simonwalsh @revolunet I went ahead with the merge, fixed the tests and merged in a little something of my own while I was at it. I've also bumped the version to 0.0.12 and pushed the new tag.

**Comment by revolunet** [comment]
that's awesome, thank you @tsov for a great addition and @deltaepsilon for review !

**Comment by simonwalsh** [comment]
Thanks guys!

**Comment by revolunet** [comment]
@tsov hi! is it possible please to add a small usage example in the readme ?

**Comment by tsov** [comment]
@revolunet Sure, will do! Thanks guys

**Comment by tsov** [comment]
https://github.com/revolunet/angular-google-analytics/pull/63

**Pull request merged**
