### PR TITLE
Re-write of README and fixes for multi-tracker behaviors

### PR DESCRIPTION
**Pull request by justinsa**
* Full re-write of README for better understanding of how things work and improved comprehension by reader. Added new functionality and improved overall structure.

* This change is NOT backwards compatible for how multiple trackers, event tracking, and e-commerce work with universal analytics. README addresses correct usage moving forward.

### CODE REVIEW

**Comment by justinsa** [comment]
@revolunet, can you add me to the CodeShip project as a Collaborator? You should be able to use my Github account since I am a collaborator on the repository. Thanks!

**Comment by revolunet** [comment]
oops, should be ok now !

**Comment by revolunet** [comment]
wow very nice work on the README, much more readable and appealing ! :+1: :+1: :+1:

**Comment by deltaepsilon** [comment]
Oh that s nice. Great work @justinsa.

**Comment by Karpo72** [comment]
@justinsa Well in my Tests it failed.

The trackerName in the function below is always undefinded:
```javascript
set: function (name, value, trackerName) {
            that._set(name, value, trackerName);
          }
```

**Comment by Karpo72** [comment]
@justinsa I currently don't see where the trackerName is passed from

**Comment by justinsa** [comment]
@Karpo72 I think the problem you are seeing is that `master` doesn't contain a fix I added for the `set` method to expose the `trackerName` parameter. That fix is in the PR that is outstanding. I can merge the PR and then you will be able to see that in `master`. I was under the impression you were testing against the code in the PR and not `master`. I'll merge and then you can reconfirm. Thanks.

**Pull request merged**
