### PR TITLE
Use universal analytics by default

### LINKED ISSUE #68: Use analytics.js by default
It took me some time to understand that I had to call AnalyticsProvider.useAnalytics(true) to make it work. I think it would be easier if analytics was used by default.

### PR DESCRIPTION
**Pull request by justinsa**
Fix #68, #91

* universal analytics is now the default option.
* set method now exposes a trackerName parameter.
* put configuration values into an exposed object off of the Analytics service.
* Add missing methods and properties to README.

### CODE REVIEW

**Comment by justinsa** [comment]
@nanocom, @stramel, @karpo72. This PR addresses issues brought up or endorsed by yourself. A code review would be appreciated.

**Comment by Karpo72** [comment]
@justinsa I'll do a test tomorrow

**Comment by stramel** [comment]
From looking at the code it looks good to me, I won't have time to test it so :+1:

**Comment by justinsa** [comment]
Merging as code is approved.

**Pull request merged**
