### PR TITLE
Add support for custom set commands on accounts

### LINKED ISSUE #71: Dynamically set the UA Account as the route changes?
I'm using ui-router and need to change the UA account based on the route. Is there a mechanism to do this currently?

### LINKED ISSUE #116: Ability to set forceSSL or other custom fields on provider
I would like to run this: ga('set', 'forceSSL', true);
Using something like this: AnalyticsProvider.set('forceSSL',true);
I know I can do: Analytics.set('forceSSL',true);
However this wont get sent until after the first few calls which means they won't all be over ssl. It would be nice to be able to set custom fields on the provider

### PR DESCRIPTION
**Pull request by justinsa**
Fixes #71, #116
* Support for custom set commands that are run immediately after account object
creation.
* Support for a custom select function on each account object that can disable a tracker by returning false.

### CODE REVIEW

**Comment by justinsa** [comment]
Will leave open for a couple of days before merging and publishing. @offsky, this implements the feature you were requesting as a more general solution. Set commands are permitted to be account specific and hence this pushes you to use the account object to customize for your scenario. Please see the README and additional unit test I added for clarification.

**Comment by justinsa** [comment]
@sonicparke the second part of this PR contains the feature you wanted in #71. Please have a review and provide any feedback you might have. Thanks.

**Comment by offsky** [comment]
This looks good. It will resolve my issue completely.

**Comment by justinsa** [comment]
Merging as no response on original commit in 2 days and sign-off received on the second feature addition by @offsky.

**Pull request merged**
